### ISSUE TITLE
Issue with sidebar not loading

### ISSUE THREAD

**Issue by damianesteban** [HippoLabs-UK/terraform-aws-metabase#3]
This module is excellent, it is exactly what I needed. However, when I start up metabase I get an infinite loading state in the sidebar on the left - any idea what could be causing this?

Thanks.

**Comment by damianesteban** [comment]
This was due to an ad blocker.

**Comment by enikovarga** [comment]
Thank you! Glad to hear that you found the module helpful and managed to resolve the issue.
