### ISSUE TITLE
Great stuff! What are the monthly costs for this infrastructure?

### ISSUE THREAD

**Issue by frankbecker** [HippoLabs-UK/terraform-aws-metabase#4]
Any ideas as to how much this costs every month? Thank you in advance.

**Comment by enikovarga** [comment]
@frankbecker with the default settings of running a micro ec2 instance and a small db instance, it should cost you around $70 a month.

**Comment by alimcmaster1** [comment]
@frankbecker - let us know how you get on! Interested to hear any feedback too :)
