### ISSUE TITLE
Initial user

### ISSUE THREAD

**Issue by kmogilevskii** [HippoLabs-UK/terraform-aws-metabase#5]
I spawn up the metabase with your module, but stuck at the log-in page, as I don't have any credentials. Is there a way to create them? I see only the RDS DB password that can be setup via secret manager.

**Comment by kmogilevskii** [comment]
resolved

**Comment by enikovarga** [comment]
When Metabase is launched for the first time, it should give you the welcome page and guide you through setting up the admin account. Glad you were able to resolve the issue!
